--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app.kubernetes.io/name: devops-nginx
  name: nginx-deployment
spec: 
  replicas: 5
  selector: 
    matchLabels: 
      app.kubernetes.io/name: devops-nginx
  template: 
    metadata: 
      labels: 
        app.kubernetes.io/name: devops-nginx
    spec: 
      containers: 
        - name: nginx
          image: nginx:1.20.0
          ports: 
            - containerPort: 80
              protocol: TCP
              name: http
---
apiVersion: v1
kind: Service
metadata: 
  labels: 
    #  add the annotation for the 10Mbps LB
    app.kubernetes.io/name: devops-nginx
  name: nginx-service
spec: 
  ports: 
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector: 
    app.kubernetes.io/name: devops-nginx
  type: LoadBalancer