apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: devops-nginx
  name: nginx-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: devops-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: devops-nginx
    spec:
      containers:
      - image: nginx
        name: nginx:1.20.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app.kubernetes.io/name: devops-nginx
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app.kubernetes.io/name: devops-nginx
  type: LoadBalancer
